apiVersion: apps/v1
kind: Deployment
metadata:
  name: oktfd7mdh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oktfd7mdh
  template:
    metadata:
      labels:
        app: oktfd7mdh
    spec:
      containers:
      - image: okteto.dev/oktfd7mdh:latest
        name: oktfd7mdh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "fcde2d54-fbc5-4a69-a140-3e8e77c522fb"
        - name: Vless_Path
          value: "/fcde2d54-fbc5-4a69-a140-3e8e77c522fb-vless"
        - name: Vmess_UUID
          value: "fcde2d54-fbc5-4a69-a140-3e8e77c522fb"
        - name: Vmess_Path
          value: "/fcde2d54-fbc5-4a69-a140-3e8e77c522fb-vmess"
        - name: Trojan_UUID
          value: "fcde2d54-fbc5-4a69-a140-3e8e77c522fb"
        - name: Trojan_Path
          value: "/fcde2d54-fbc5-4a69-a140-3e8e77c522fb-trojan"
        - name: SS_UUID
          value: "fcde2d54-fbc5-4a69-a140-3e8e77c522fb"
        - name: SS_Path
          value: "/fcde2d54-fbc5-4a69-a140-3e8e77c522fb-ss"
        - name: Share_Path
          value: "/fcde2d54-fbc5-4a69-a140-3e8e77c522fb-share"
